### PR TITLE
Change and improve user profile

### LINKED ISSUE #300: Woocommerce can't change user password
Hi, in Woocommerce /my-account there is an option 'account details'. There you have the option to change your password. This fails as current password can't be validated by Woocommerce

### LINKED ISSUE #310: auth0 forgot password doesn't change WP password
When a user initiates a new password via the _forgot password_ procedure, the new password is well registered in auth0 database but not in WP database. It should be synchronized for website using both auth0 and standard WP authentication.

### LINKED ISSUE #375: Profile password update changes
### Edit profile should check password policy and reject if unacceptable

Right now, non-implicit installs can update their password from their own WordPress profile. This will update if that password follows the password policy set on the DB connection being used. But, if the password fails, the WordPress password is updated but not the Auth0 one and there are no errors. 

Probably the fastest way to get this running like it should is a check during edit profile update and rejection if Auth0 does not accept it. Probably here:

https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_EditProfile.php#L36

Might need to merge the `update_change_password()` method just below so it passes if Auth0 is changed and does not if not. 

### Admin edit profile password changes should be allowed 

Right now, admins can change user passwords but they are not mapped to Auth0. It looks like it's just a matter of adding hooks to display and process for admins as well. 

To display, hook `edit_user_profile` with the `show_change_password` method; to validate and save, hook `personal_options_update`/`user_profile_update_errors` to the `validate_new_password`/`update_change_password` methods.

### PR DESCRIPTION
**Pull request by joshcanhelp**
Improve the user profile to send password changes to Auth0 in all cases, stop password changes if they do not meet the security policy, move all in-line profile JS to an external file, TESTS. Uses the Management API framework merged in #537.

**Specific Changes:**

- Extract all JS out of `WP_Auth0_EditProfile` and into an external JS file `assets/js/edit-user-profile.js` using `wp_localize_script` for PHP-generated data; add `WP_Auth0_EditProfile::admin_enqueue_scripts()` to load that JS on the user profile and profile edit pages. 
- Move `WP_Auth0_EditProfile::validate_new_password()` to a new method `WP_Auth0_Profile_Change_Password::validate_new_password` and improve to check for a failed password update and stop WordPress from updating if so; tie this to `validate_password_reset` so password reset attempts are sent and checked as well. 
- Moved `WP_Auth0_EditProfile::delete_user_data()` and `WP_Auth0_EditProfile::delete_mfa()` to `WP_Auth0_Profile_Delete_Data::delete_user_data` and `WP_Auth0_Profile_Delete_Mfa::delete_mfa()` respectively; add nonce and capability checks to both methods for more robust error handling.
- Add `WP_Auth0_Api_Change_Password` to send password changes to Auth0. 
- Add `WP_Auth0_Api_Delete_User_Mfa` to delete an MFA provider for a user on Auth0.
- Don't load Lock on the password reset screen of wp-login.php

**Note to reviewers:**

This is a large change but almost 60% is new tests to reach diff coverage of ~100%.

Closes #300
Closes #310 
Closes #375

### CODE REVIEW

**Comment by cocojoe** [comment]
Will review once other merged and rebased.

File: WP_Auth0.php [hunk 1]
```diff
@@ -123,7 +123,15 @@ public function init() {
 		$this->social_amplificator = new WP_Auth0_Amplificator( $this->db_manager, $this->a0_options );
 		$this->social_amplificator->init();
 
-		$edit_profile = new WP_Auth0_EditProfile( $this->db_manager, $users_repo, $this->a0_options );
+		$api_change_password = new WP_Auth0_Api_Change_Password( $this->a0_options );
```
Comment (joshcanhelp) [inline WP_Auth0.php]: Adding dependency injection to assist with testing.

File: WP_Auth0.php [hunk 2]
```diff
@@ -420,7 +428,7 @@ public function render_form( $html ) {
 		// Do not show Auth0 form when ...
 		if (
 			// .. processing lost password
-			( isset( $_GET['action'] ) && $_GET['action'] == 'lostpassword' )
+			( isset( $_GET['action'] ) && in_array( $_GET['action'], array( 'lostpassword', 'rp' ) ) )
```
Comment (joshcanhelp) [inline WP_Auth0.php]: Make sure we can still reset the password if stuck.

File: assets/js/edit-user-profile.js [hunk 3]
```diff
@@ -0,0 +1,81 @@
+/* global jQuery, wpa0UserProfile, alert */
```
Comment (joshcanhelp) [inline assets/js/edit-user-profile.js]: Moving in all inline JS from user profile.

File: lib/WP_Auth0_EditProfile.php [hunk 4]
```diff
@@ -1,48 +1,194 @@
...
+	/**
+	 * WP_Auth0_EditProfile constructor.
+	 *
+	 * @param WP_Auth0_DBManager           $db_manager - WP_Auth0_DBManager instance.
+	 * @param WP_Auth0_UsersRepo           $users_repo - WP_Auth0_UsersRepo instance.
+	 * @param WP_Auth0_Options             $a0_options - WP_Auth0_Options instance.
+	 * @param WP_Auth0_Api_Change_Password $api_change_password - WP_Auth0_Api_Change_Password instance.
+	 * @param WP_Auth0_Api_Delete_User_Mfa $api_delete_mfa - WP_Auth0_Api_Delete_User_Mfa instance.
+	 */
+	public function __construct(
```
Comment (joshcanhelp) [inline lib/WP_Auth0_EditProfile.php]: Adding dependency injection.

File: lib/WP_Auth0_EditProfile.php [hunk 5]
```diff
@@ -1,48 +1,194 @@
...
 
-		add_action( 'show_user_profile', array( $this, 'show_change_password' ) );
-		add_action( 'personal_options_update', array( $this, 'update_change_password' ) );
-		add_filter( 'user_profile_update_errors', array( $this, 'validate_new_password' ), 10, 3 );
+		add_action( 'user_profile_update_errors', array( $this, 'validate_new_password' ), 10, 2 );
+		add_action( 'validate_password_reset', array( $this, 'validate_new_password' ), 10, 2 );
 
 		if ( $pagenow == 'profile.php' || $pagenow == 'user-edit.php' ) {
-			add_action( 'admin_footer', array( $this, 'disable_email_field' ) );
+			add_action( 'admin_enqueue_scripts', array( $this, 'admin_enqueue_scripts' ) );
```
Comment (joshcanhelp) [inline lib/WP_Auth0_EditProfile.php]: Move all JS to an external file, see above.

File: WP_Auth0.php [hunk 6]
```diff
@@ -123,9 +123,22 @@ public function init() {
 		$this->social_amplificator = new WP_Auth0_Amplificator( $this->db_manager, $this->a0_options );
 		$this->social_amplificator->init();
 
+		$api_client_creds = new WP_Auth0_Api_Client_Credentials( $this->a0_options );
+
 		$edit_profile = new WP_Auth0_EditProfile( $this->db_manager, $users_repo, $this->a0_options );
 		$edit_profile->init();
 
+		$api_change_password = new WP_Auth0_Api_Change_Password( $this->a0_options, $api_client_creds );
```
Comment (joshcanhelp) [inline WP_Auth0.php]: Dependency injection for classes using the new API framework.

File: lib/WP_Auth0_EditProfile.php [hunk 7]
```diff
@@ -1,38 +1,102 @@
...
+	 * Add actions and filters for the profile page.
+	 */
 	public function init() {
-		global $pagenow;
-
+		add_action( 'admin_enqueue_scripts', array( $this, 'admin_enqueue_scripts' ) );
 		add_action( 'personal_options_update', array( $this, 'override_email_update' ), 1 );
+	}
 
-		add_action( 'edit_user_profile', array( $this, 'show_delete_identity' ) );
```
Comment (joshcanhelp) [inline lib/WP_Auth0_EditProfile.php]: Moving to individual classes

File: lib/api/WP_Auth0_Api_Delete_User_Mfa.php [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+		WP_Auth0_Api_Client_Credentials $api_client_creds
+	) {
+		parent::__construct( $options );
+		$this->api_client_creds = $api_client_creds;
+	}
+
+	/**
+	 * Set the user_id and provider, set the authorization header, call the API, and handle the response.
+	 *
+	 * @param string|null $user_id - Auth0 user ID to delete the MFA provider.
```
Comment (cocojoe) [inline lib/api/WP_Auth0_Api_Delete_User_Mfa.php]: Should we mention in docheader that the default MFA provider is google-authenticator?

Comment (joshcanhelp) [reply lib/api/WP_Auth0_Api_Delete_User_Mfa.php]: @cocojoe - Function params default there and it's mostly an internally-used functionality.
