### PR TITLE
Fix VIP Go MFA screen

### LINKED ISSUE #687: WordPress.com VIP Go MFA incompatibility
### Description

WordPress.com VIP Go will be requiring all users that have edit posts capabilities to use their MFA system as of May 29, 2019. If a user on a VIP Go site configures MFA on their account, they can no longer log in using Auth0, as the authentication flow presents a white screen when the MFA prompt should appear.

Although there are filters to disable the requirement for users to use MFA on VIP Go sites, users are still able to configure MFA on their profile, and if a user has MFA active, it will lock them out of their account when attempting to log in using Auth0.

This is a particular problem on multisite networks, in which Auth0 may not be used for login on all sites in the network, and MFA would be configured on the network-level account for non-Auth0 sites. A common use case here would be where the root site in the network is a corporate website where only employees will be logging in using their WordPress credentials with MFA configured, and one of the subsites supports public registration using Auth0 for community engagement.

### Prerequisites

* [X] Have you read [Auth0's general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)?
* [X] Have you read [Auth0's code of conduct guidelines](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [X] Did you check the [documentation](https://auth0.com/docs/cms/wordpress/)?
* [X] Did you check the [Auth0 Community](https://community.auth0.com/tags/wordpress)?
* [X] Did you check the [WP.org Support Forum](https://wordpress.org/support/plugin/auth0)?
* [X] Are there any related or duplicate [Issues](https://github.com/auth0/wp-auth0/issues) or [PRs](https://github.com/auth0/wp-auth0/pulls) in this repo?

### Environment

Please provide the following:

* WP-Auth0 version: 3.10.0
* WordPress version: 5.2
* PHP version: 7.3
* Browser version, if applicable: Chrome Mac 74.0.3729.131
* Additional active plugins that might be relevant: VIP Go mu-plugins: https://github.com/Automattic/vip-go-mu-plugins

### Reproduction

On a site that is using VIP Go mu-plugins (all sites on the WordPress.com VIP Go platform), configure a user account with MFA at the bottom of the user's profile page (/wp-admin/profile.php#two-factor-options), then attempt to sign in using Auth0 in an incognito window.

I used the "sign in with Google" button, and it took me through the authentication process with Google, and when it redirected back to the site it yields a nearly empty page - there is just a link for "back to [site name]". I have MFA configured with WordPress.com VIP Go via email, and I confirmed that the MFA email was sent from my VIP Go site, but the prompt to enter the MFA code is not present, and I am not able to finish the login process to the site.

This error is consistently reproducible.

There are no PHP or Auth0 plugin error log entries.

JSON export of settings: https://gist.github.com/kevinfodness/635e68236d5ffc6bc76da87b50842a91

Screenshot of nearly blank screen after returning from Auth0 login workflow:

Back to [SITE NAME]

### PR DESCRIPTION
**Pull request by joshcanhelp**
### Changes

Add a query var during Auth0 login to indicate the status of the process globally. This allows for the VIP MFA form to show instead of a redirect (ULP) or Auth0 form showing (embedded). Also switches all uses of `WP_Auth0_Options::Instance()->can_show_wp_login_form()` to `wp_auth0_can_show_wp_login_form()`.

### References

Closes #687 

### Testing

* [x] This change adds unit test coverage
* [x] This change has been tested on WP 5.2.1

### Checklist

* [ ] All existing and new tests complete without errors
* [x] All code quality tools/guidelines in the [Contribution guide](CONTRIBUTION.md) have been run/followed
* [ ] All active GitHub CI checks have passed

### CODE REVIEW

File: functions.php [hunk 1]
```diff
@@ -31,7 +31,10 @@ function wp_auth0_get_option( $key, $default = null ) {
 function wp_auth0_is_current_login_action( array $actions ) {
 
 	// Not on wp-login.php.
-	if ( ! isset( $GLOBALS['pagenow'] ) || 'wp-login.php' !== $GLOBALS['pagenow'] ) {
+	if (
+		( isset( $GLOBALS['pagenow'] ) && 'wp-login.php' !== $GLOBALS['pagenow'] ) &&
```
Comment (lbalmaceda) [inline functions.php]: no longer an OR, is this desired?

Comment (joshcanhelp) [reply functions.php]: This is desired. Need to either have that page set to `wp-login.php` or that function. If the page has the function, it will not be the wp-login.php `pagenow`
