### PR TITLE
Fix import-export tabs not working

### LINKED ISSUE #484: TypeError: jQuery(...).tab is not a function
`TypeError: jQuery(...).tab is not a function admin.php:689:5`

When in `/wp-admin` > `Auth0` > `Import-Export settings` clicking on the Export Settings tab causes this JS error and the page does not appear.

Running wp-auth0 v3.6.1

### PR DESCRIPTION
**Pull request by joshcanhelp**
Fixes #484

### CODE REVIEW

File: assets/js/admin.js [hunk 1]
```diff
@@ -57,6 +57,19 @@ jQuery(document).ready(function($) {
...
+    /*
+    Import and Export settings tabs
+     */
+    $('.js-a0-upload-toggle').click(function(){
+        $('#js-a0-upload-file').toggle();
+        $('#js-a0-paste-json').toggle();
+    });
+
+    $('.js-a0-import-export-tabs').click(function (e) {
+        e.preventDefault();
```
Comment (lbalmaceda) [inline assets/js/admin.js]: what's this line doing and why does this function returns an error while the other above doesn't?

Comment (joshcanhelp) [reply assets/js/admin.js]: The HTML is an `<a>` tag so we don't want it to act like a link. 

This function does not return an error ... it doesn't return anything. `e` is for `event`, so stop the default event.
